[build]
builder = "nixpacks"

[deploy]
# We remove the migrations for now just to get the 'Active' green light
startCommand = "uvicorn backend.app:app --host 0.0.0.0 --port ${PORT:-8080}"

# Increase this to give it more time to breathe
healthcheckTimeout = 600 
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10