"""add_phase3_columns

Revision ID: 1a3528eeacab
Revises: f7b5aa4c8050
Create Date: 2026-03-17 18:18:19.323908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3528eeacab'
down_revision: Union[str, Sequence[str], None] = 'f7b5aa4c8050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 0. Clean slate: Drop the type if it was partially created
    op.execute("DROP TYPE IF EXISTS readingstatus CASCADE")

    # ### commands auto generated by Alembic ###
    op.drop_table('playing_with_neon')
    
    op.add_column('airesult', sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='1.0'))
    
    op.alter_column('airesult', 'patient_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('airesult', 'clinician_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('airesult', 'student_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
               
    # --- START READING_STATUS FIX ---
    # 1. Create the Enum type explicitly with LOWERCASE values
    reading_status_enum = postgresql.ENUM('unread', 'reading', 'done', 'flagged', name='readingstatus')
    reading_status_enum.create(op.get_bind())

    # 2. Force all existing data to lowercase so it matches the Enum
    op.execute("UPDATE study SET reading_status = LOWER(reading_status)")

    # 3. Drop default and convert using explicit lowercase cast
    op.execute("ALTER TABLE study ALTER COLUMN reading_status DROP DEFAULT")
    
    op.alter_column('study', 'reading_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('unread', 'reading', 'done', 'flagged', name='readingstatus'),
               existing_nullable=False,
               postgresql_using='LOWER(reading_status)::readingstatus')
               
    # 4. Set the default
    op.execute("ALTER TABLE study ALTER COLUMN reading_status SET DEFAULT 'unread'::readingstatus")
    # --- END READING_STATUS FIX ---

    op.create_index(op.f('ix_study_reading_status'), 'study', ['reading_status'], unique=False)
    
    op.alter_column('studymetrics', 'risk_of_bias',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('studymetrics', 'pico_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('studymetrics', 'statistical_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('studymetrics', 'statistical_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('studymetrics', 'pico_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('studymetrics', 'risk_of_bias',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_study_reading_status'), table_name='study')
    
    op.alter_column('study', 'reading_status',
               existing_type=sa.Enum('unread', 'reading', 'done', 'flagged', name='readingstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'unread'::character varying"),
               postgresql_using='reading_status::text')
               
    op.alter_column('airesult', 'student_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('airesult', 'clinician_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('airesult', 'patient_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('airesult', 'prompt_version')
    op.execute("DROP TYPE IF EXISTS readingstatus")