"""initial schema with AIResult and StudyMetrics fixes

Revision ID: 23556bd598dd
Revises: 
Create Date: 2026-03-09 19:00:00.335493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23556bd598dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studymetrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('folder_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ai_runs', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studymetrics', schema=None) as batch_op:
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('ai_runs')
        batch_op.drop_column('comment_count')
        batch_op.drop_column('folder_count')
        batch_op.drop_column('save_count')

    # ### end Alembic commands ###
